spring:
  application:
    name: order-db-migration

  datasource:
    url: jdbc:postgresql://localhost:6541/order-db
    hikari:
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    test-rollback-on-update: false